# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoData.proto',
  package='com.netpro.trinity.trinity.python.proto',
  syntax='proto2',
  serialized_options=b'\n\'com.netpro.trinity.trinity.python.protoB\tProtoDataH\001',
  serialized_pb=b'\n\x0fProtoData.proto\x12\'com.netpro.trinity.trinity.python.proto\"\xcf\x01\n\x08\x44MRecord\x12\x0e\n\x06signal\x18\x01 \x02(\t\x12M\n\x06\x63olumn\x18\x02 \x03(\x0b\x32=.com.netpro.trinity.trinity.python.proto.DMRecord.ColumnEntry\x1a\x64\n\x0b\x43olumnEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.com.netpro.trinity.trinity.python.proto.DMMetaColumn:\x02\x38\x01\"\xc4\x01\n\x0c\x44MMetaColumn\x12P\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32>.com.netpro.trinity.trinity.python.proto.DMMetaColumn.DataType\x12\x12\n\nbinaryData\x18\x02 \x01(\x0c\"N\n\x08\x44\x61taType\x12\n\n\x06STRING\x10\x00\x12\x07\n\x03INT\x10\x01\x12\t\n\x05VIDEO\x10\x02\x12\x07\n\x03JPG\x10\x03\x12\x07\n\x03PNG\x10\x04\x12\x07\n\x03\x44OC\x10\x05\x12\x07\n\x03TXT\x10\x06\x42\x36\n\'com.netpro.trinity.trinity.python.protoB\tProtoDataH\x01'
)



_DMMETACOLUMN_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='com.netpro.trinity.trinity.python.proto.DMMetaColumn.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPG', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOC', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TXT', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=389,
  serialized_end=467,
)
_sym_db.RegisterEnumDescriptor(_DMMETACOLUMN_DATATYPE)


_DMRECORD_COLUMNENTRY = _descriptor.Descriptor(
  name='ColumnEntry',
  full_name='com.netpro.trinity.trinity.python.proto.DMRecord.ColumnEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.netpro.trinity.trinity.python.proto.DMRecord.ColumnEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.netpro.trinity.trinity.python.proto.DMRecord.ColumnEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=268,
)

_DMRECORD = _descriptor.Descriptor(
  name='DMRecord',
  full_name='com.netpro.trinity.trinity.python.proto.DMRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='com.netpro.trinity.trinity.python.proto.DMRecord.signal', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column', full_name='com.netpro.trinity.trinity.python.proto.DMRecord.column', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DMRECORD_COLUMNENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=268,
)


_DMMETACOLUMN = _descriptor.Descriptor(
  name='DMMetaColumn',
  full_name='com.netpro.trinity.trinity.python.proto.DMMetaColumn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataType', full_name='com.netpro.trinity.trinity.python.proto.DMMetaColumn.dataType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binaryData', full_name='com.netpro.trinity.trinity.python.proto.DMMetaColumn.binaryData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DMMETACOLUMN_DATATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=467,
)

_DMRECORD_COLUMNENTRY.fields_by_name['value'].message_type = _DMMETACOLUMN
_DMRECORD_COLUMNENTRY.containing_type = _DMRECORD
_DMRECORD.fields_by_name['column'].message_type = _DMRECORD_COLUMNENTRY
_DMMETACOLUMN.fields_by_name['dataType'].enum_type = _DMMETACOLUMN_DATATYPE
_DMMETACOLUMN_DATATYPE.containing_type = _DMMETACOLUMN
DESCRIPTOR.message_types_by_name['DMRecord'] = _DMRECORD
DESCRIPTOR.message_types_by_name['DMMetaColumn'] = _DMMETACOLUMN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DMRecord = _reflection.GeneratedProtocolMessageType('DMRecord', (_message.Message,), {

  'ColumnEntry' : _reflection.GeneratedProtocolMessageType('ColumnEntry', (_message.Message,), {
    'DESCRIPTOR' : _DMRECORD_COLUMNENTRY,
    '__module__' : 'ProtoData_pb2'
    # @@protoc_insertion_point(class_scope:com.netpro.trinity.trinity.python.proto.DMRecord.ColumnEntry)
    })
  ,
  'DESCRIPTOR' : _DMRECORD,
  '__module__' : 'ProtoData_pb2'
  # @@protoc_insertion_point(class_scope:com.netpro.trinity.trinity.python.proto.DMRecord)
  })
_sym_db.RegisterMessage(DMRecord)
_sym_db.RegisterMessage(DMRecord.ColumnEntry)

DMMetaColumn = _reflection.GeneratedProtocolMessageType('DMMetaColumn', (_message.Message,), {
  'DESCRIPTOR' : _DMMETACOLUMN,
  '__module__' : 'ProtoData_pb2'
  # @@protoc_insertion_point(class_scope:com.netpro.trinity.trinity.python.proto.DMMetaColumn)
  })
_sym_db.RegisterMessage(DMMetaColumn)


DESCRIPTOR._options = None
_DMRECORD_COLUMNENTRY._options = None
# @@protoc_insertion_point(module_scope)
